image: registry.gitlab.com/aboutyou/cloud-agency/infrastructure/docker-images/ci/node:16.13.2-alpine3.15

cache:
  paths:
    - node_modules/

stages:
  - test

check_build:
  stage: test
  script:
    - apk update && apk upgrade && apk add --no-cache bash git openssh
    - yarn install
    - yarn check-format
    - yarn test
  tags:
    - docker
