image: registry.gitlab.com/aboutyou/cloud-agency/infrastructure/docker-images/ci/node:16.13.2-alpine3.15

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

package:
  stage: build
  before_script:
    - apk update && apk upgrade && apk add --no-cache bash git openssh
    - npm install
  script:
    - npm run build
  tags:
    - ay-shared-runner
lint:
  stage: test
  script:
    - npm run lint
  tags:
    - ay-shared-runner

Unit tests:
  stage: test
  script:
    - npm run test
  tags:
    - ay-shared-runner
