image: node:16-alpine3.15

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

package:
  stage: build
  before_script:
    - apk update && apk upgrade && apk add --no-cache bash git openssh
    - yarn install
  script:
    - yarn run build
  tags:
    - ay-shared-runner

Test & Lint:
  stage: test
  script:
    - yarn run test
  tags:
    - ay-shared-runner
